import OpenAI from "openai";
import { TwitterApi } from "twitter-api-v2";
import fs from "node:fs";
import "dotenv/config";

const openai = new OpenAI();

const twitterClient = new TwitterApi({
	appKey: process.env.X_API_KEY,
	appSecret: process.env.X_API_SECRET,
	accessToken: process.env.X_ACCESS_TOKEN,
	accessSecret: process.env.X_ACCESS_SECRET,
});

const prompt = `
Génères moi une image abstraite au format carré, de style techno-constructiviste, presque machine-based. L'image contient des formes géométriques récurrentes, qui apparaissent sur l'image en différentes strates et hiérarchies.

Choix graphique : 
- Formes nettes, géométriques (rectangles, cercles, barres, carrés, etc).
- Palette limitée : noir (code brut), bleu (signal / metadata), blanc cassé (support). 
- Disposition par quadrants / lignes imbriquées : En référence aux sections internes d’un fichier PNG (IHDR, IDAT, etc.), suggérant une machine lisible ou un système ordonné.

Tu optes pour un rendu vectoriel propre, froid, systématique, où le sens ne vient ni de la beauté, ni de l’émotion, mais de l’ordre, des formes, de la répétition – ce qui évoque la logique du binaire, de l’encodage.
`;

async function run() {
	try {
		console.log("Tâche cron démarrée");

		const result = await openai.images.generate({
			model: "gpt-image-1",
			prompt,
			size: "1024x1024",
			quality: "medium",
		});

		const image_base64 = result.data[0].b64_json;
		const image_bytes = Buffer.from(image_base64, "base64");
		const id = Date.now();
		const filePath = `outputs/Abstract-${id}.png`;

		fs.writeFileSync(filePath, image_bytes);
		console.log(`Image sauvegardée : ${filePath}`);

		const mediaId = await twitterClient.v1.uploadMedia(filePath);
		await twitterClient.v2.tweet({
			text: "🌀 Generated by abstraction-bot.\n#AIart #abstract #generative",
			media: { media_ids: [mediaId] },
		});

		console.log("Image publiée sur X");
	} catch (err) {
		console.error("Erreur dans la tâche cron :", err);
	}
}

run();
